version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-stage
      args:
        NODE_ENV: development
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: ["sh", "-c", "npm install --force && npm run serve"]
