version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ["sh", "-c", "echo 'Frontend built.'"]
